name: Syphon Break - CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get --no-install-recommends -y install pkg-config libglfw3 libglfw3-dev zlib1g zlib1g-dev fontconfig libfontconfig1 libfontconfig1-dev mesa-utils mesa-common-dev

      - name: Download Mesche
        uses: mesche-lang/download-mesche@v1
        with:
          artifact-token: ${{ secrets.ARTIFACT_TOKEN }}

      - name: Debug Build
        run: ./bin/mesche build dist --config debug

      - name: Upload Debug Package
        uses: actions/upload-artifact@v2
        with:
          name: syphon-break-linux-debug
          path: dist/*

      - name: Release Build
        run: |
          rm -rf dist
          ./bin/mesche build dist --config release
          cd dist
          zip -r ../syphon-break-linux.zip *
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Syphon Break - Dev Build
          tag_name: dev
          files: syphon-break-linux.zip
